-- Insert data into the table with generated UUIDs for the id column
INSERT INTO "OpenEnergyBillRule" ("id", "value", "transactionUType", "field") VALUES
('slpwha27oqucqyw55f50dqrj', 'Re-energisation (Recipient Discretion)', 'otherCharges', 'description'),
('xwgey4fzroxobtoro3t0vsjl', 'GST', 'onceOff', 'description'),
('cqyd6v6aul5g3sg35z4efwsb', 'AUS GOV ENERGY BILL RELIEF', 'onceOff', 'description'),
('ipisx2861we5rugzk5e72zvg', 'Government Rebate', 'otherCharges', 'description'),
('u4xb31ukszwy7yshffjkq8u9', 'CREDIT', 'onceOff', 'description'),
('cng4g2e33n4qkbm6je3fdipb', 'Small balance credit', 'otherCharges', 'description'),
('prdp6gjrve7ijz4v324ttxbk', '* Additional Balance Plan (Home)    Discount - 9%', 'otherCharges', 'description'),
('t8za0ftd6gadflnp2g2sd5bz', 'PowerResponse event credit 14-07-2023', 'onceOff', 'description'),
('v4hohp9iwwzebv654ca25a6y', '* Reconnection - Bus Hrs', 'onceOff', 'description'),
('xfx7zazeqat86il6wyaid5qk', 'Interest Reward', 'otherCharges', 'description'),
('w18skari7i24pjbqny22hmtd', 'Solar Tariff Adjustment', 'onceOff', 'description'),
('r5hlvxy5cpegx4kofzrfd2nr', 'GSL Credit from DB SAPN-CR', 'otherCharges', 'description'),
('osrppbxudu73hergy6wwif6k', 'Daily Supply Charge', 'otherCharges', 'description'),
('mhj8jt1dydzrcd9zettr811e', 'May Future Savings', 'onceOff', 'description'),
('tzooxzzly8vd7n9vbrdf2p8e', 'Serv to Prop x 93 Days', 'otherCharges', 'description'),
('z6ltk21w0x021scajgkeszl5', '* Additional Flexi Plan (Home)    Discount - 5%', 'otherCharges', 'description'),
('gjr1ce206cgbfw1fp60yzg7p', 'GST Rounding Adjustment', 'otherCharges', 'description'),
('of46xsj90pfffdubrvzta28e', 'February Future Savings', 'onceOff', 'description'),
('no3gx99uen96toq3k4eihvo4', 'Serv to Prop x 70 Days', 'otherCharges', 'description'),
('w1c2gvkg55dqsusepa71lb65', '* 20% Discount on Usage for Paying Your Last Bill by the due date', 'onceOff', 'description'),
('upejl1q9oqka4v71ibt7c510', 'GOVERNMENT_ENERGY_RELIEF_REBATE_FY25', 'otherCharges', 'description'),
('dm2dd8vs2ndvzellpw186lge', 'Australian Government Energy Bill Relief', 'onceOff', 'description'),
('lrnq4fypk7c9lnpahz5y9i8v', 'PowerResponse event credit 14-12-2023', 'onceOff', 'description'),
('y2r0fg88j5lpjmxf9ejumlu1', 'June Future Savings', 'onceOff', 'description'),
('o97fnbxiraorm2mdoqfsig0a', 'Serv to Prop x 96 Days', 'otherCharges', 'description'),
('cjyjyknbduqyonvppeboqlpj', 'Visa debit card payment fee', 'otherCharges', 'description'),
('q824ztrn05zuecuz8as2tyjt', 'PowerResponse event credit 29-02-2024', 'onceOff', 'description'),
('a2bpxms3pnsssr7dghqi9aqj', 'March Future Savings', 'onceOff', 'description'),
('q8akwbns9pblrmho52oie62e', '* NSW Gvt Household Rebate', 'otherCharges', 'description'),
('jzlj5q7h2d8e9kiw3c4dnb2l', 'Spring Ahead Future Pack', 'onceOff', 'description'),
('q43yzc5t7ixo3ypl08yjm6h9', 'AUS Gov Energy Relief', 'onceOff', 'description'),
('lg9kpl80wh5ieamqe3rog0lu', 'April Future Savings', 'onceOff', 'description'),
('rt01hccwfnmdswnbv1ptln2n', 'Bill', 'onceOff', 'description'),
('cgzs1morlewt70wccqty028e', 'PAYMENT_FEE', 'onceOff', 'description'),
('knnure38a4mlodggf27e58c1', 'GOVERNMENT_ENERGY_RELIEF_REBATE_QLD', 'otherCharges', 'description'),
('z7v9vm96ss2max0xcvw2vi2t', '* Flexi Saver Supply Charge', 'otherCharges', 'description'),
('m3asyuxxdamlpfv5dvzze3tw', 'January Future Savings', 'onceOff', 'description'),
('jgoq1d2el71uxfkyk9ykf0ux', 'August Future Savings', 'onceOff', 'description'),
('xsigkrlzno7q4qayfsb3b788', 'Service Order (Re-energisation), NMI: 41035490985', 'onceOff', 'description'),
('txvyo6vghtzwe4zaobdpltqc', 'Late payment fee - DR', 'otherCharges', 'description'),
('zymza6sk62ez1d3k90ul0cws', 'Serv to Prop x 19 Days', 'otherCharges', 'description'),
('d8v6nxtldfhk5a35s1zpf6d1', '* Additional Flexi Plan (Home)    Discount - 18%', 'otherCharges', 'description'),
('he419621ktpmbqs8862jjda8', 'Supply Charges', 'otherCharges', 'description'),
('ll1vo4fg638sq6axl2ftcrft', 'Transfer credit', 'otherCharges', 'description'),
('j8zvrnj16ikeqwfqa6tos7s0', 'November Future Savings', 'onceOff', 'description'),
('tqmfj7tmtrig9y7e2t7lww81', 'Late Payment Fee', 'onceOff', 'description'),
('f7cafpuzscjbw11x11admvmo', 'Visa credit card payment fee', 'otherCharges', 'description'),
('ul8enk98nt0y06v8m7a0j81z', 'Master debit card payment fee', 'otherCharges', 'description'),
('noud919ptn6xl69io3etqbbu', 'BONUS', 'onceOff', 'description'),
('wcwjjxlv2htwdrlqpo5gk9wf', '* Additional Flexi Plan (Home)    Discount - 10%', 'otherCharges', 'description'),
('rb6tageiegmsjyay2ejj5x9a', 'Account Adjustments', 'onceOff', 'description'),
('u2rp3ufxau1d3u2is39mw3ok', 'Transfer Adjustment', 'onceOff', 'description'),
('itq4tiuahnxyxv4agrn7zf0v', 'Black Friday Powerpack', 'onceOff', 'description'),
('x96y6jtddj2pn0w0lz5bvk5t', 'NSW-AUS Gov Bill Relief', 'onceOff', 'description'),
('atjp9ucagob9f4qm2kmrbbqe', 'Daily supply charges', 'otherCharges', 'description'),
('skzuckfxn3mrwgxaipp5baus', 'LATE_PAYMENT_FEE', 'otherCharges', 'description'),
('se1cfxam6zjdtffszyj37z4p', 'October Future Powerpack', 'onceOff', 'description'),
('m872f3dfvl2rsogmkp8m7ksh', 'DISCOUNT', 'onceOff', 'description'),
('a9ue7mxoni0w22tuwpv1dwmq', '* Basic - Home Supply Charge', 'otherCharges', 'description'),
('a8i0a6g0xown6ao31hro1h4x', '* Rebate', 'onceOff', 'description'),
('zvfllktxdfo7hbvzlkkvj4m8', '* Guaranteed Service Level Adjustment', 'onceOff', 'description'),
('ye8di9o08ij1ywgf3mz58wfs', 'Australian Government Energy Price Relief Plan Rebate, payment 2 of 4', 'otherCharges', 'description'),
('d6ezroicvfhgguwl335zlmp2', 'GOVERNMENT_COST_OF_LIVING_REBATE_QLD', 'otherCharges', 'description'),
('hw6m2rlz0tt51dl8iw9jem0e', '* Go Neutral - You have registered for carbon neutral electricity at no additional cost. This takes up to 6 months to start on your account.', 'otherCharges', 'description'),
('rf3dn7764y14c5d27bcje6w5', 'Serv to Prop x 73 Days', 'otherCharges', 'description'),
('aolo08ta2px67gp6pzbrlcu2', 'Serv to Prop x 16 Days', 'otherCharges', 'description'),
('tzgamicmk7uwqx0h63ogelpw', 'Rev:AUS GOV ENERGY BILL RELIEF', 'onceOff', 'description'),
('cneymx3k9e7rq35uojesm8tp', 'Transfer debit', 'otherCharges', 'description'),
('uivrs6ywmqlvgsk35ep9amip', 'December Future Savings', 'onceOff', 'description'),
('iud2s1r6sdmjs7qsnne7zes2', '* Additional Flexi Plan (Home)    Discount - 15%', 'otherCharges', 'description'),
('ww98mk51ncoj8mze2r82ncsf', 'Welcome Credit', 'otherCharges', 'description'),
('yedlkqiw5h2pvg0t0jkto9us', 'Serv to Prop x 91 Days', 'otherCharges', 'description'),
('ui03qmj1xu5dxvuzxgfnrtv2', 'SUPPLY', 'otherCharges', 'description'),
('k2dogpltgt9ico4oahn257tr', 'REVERSED_ACCOUNT_CHARGE', 'onceOff', 'description'),
('llvhl9v5tih63u7jsqbxz6ki', '* Standing Offer (Home) Supply Charge', 'otherCharges', 'description'),
('wfu03lnv0zps6usjq2w2qtao', '* Flexi Plan (Home) Supply Charge', 'otherCharges', 'description'),
('dafzbngjhaaiv8gnzzybuf6t', '* Special meter read - Bus Hrs', 'onceOff', 'description'),
('e7jrhaktxl322j9t8p68ceck', 'CARD_PAYMENT_FEE', 'otherCharges', 'description'),
('dxyp66noigtfdmmkn5f5dj22', 'Australian Government Energy Price Relief Plan Rebate, payment 1 of 4', 'otherCharges', 'description'),
('ba5xgvtq4q78eetj2tvplifn', 'July Future Savings', 'onceOff', 'description'),
('n2lx190h8pk5g1hn9dv43xpu', 'Serv to Prop x 88 Days', 'otherCharges', 'description'),
('r71gue4gkelr33xkrlna6r7d', 'AUS Government Energy Bill Relief', 'onceOff', 'description'),
('zs2ixngouuxo605m1hgt4lf0', 'December Future Pack', 'onceOff', 'description'),
('g8c73nvhdij18hnvba3sez4p', 'Daily Charge', 'otherCharges', 'description'),
('g7eckxjv0201g8kc5grv2ahv', '* Balance Plan (Home) Supply Charge', 'otherCharges', 'description'),
('o69qpxigolgnt73f4zrveurf', 'Bill Correction', 'onceOff', 'description'),
('n1g2daok6bd4svzgv5n68khr', 'AUS GOV ENERGY PRICE RELIEF PLAN REBATE', 'onceOff', 'description'),
('zeut7908fv2xkz1yf2v8gapi', 'Pay on time discount', 'onceOff', 'description'),
('p0dh4r5wh3ijecg50f61gnvw', '* Credit Card Merchant Service Fee', 'onceOff', 'description'),
('xzkco8prtujwj5n7plprfgqs', 'September Future Savings', 'onceOff', 'description'),
('i8lctr4sw92viiljtgqq34oi', 'Re-energisation Fee', 'onceOff', 'description'),
('uopp46kejqz5cialk2m3t12n', 'Footy Finals Future Pack', 'onceOff', 'description'),
('lmxwuuyi6qsj7lswrylcjmv9', 'September Future Powerpack', 'onceOff', 'description'),
('pjfjce5vaklutgetre6i8h3a', 'November Future Powerpack', 'onceOff', 'description'),
('lr6rsdo9io6fi7u6ugpwu19a', 'OTHERS', 'onceOff', 'description');