-- AlterTable
ALTER TABLE "PLFee" ADD COLUMN     "brokerOriginationFee" DOUBLE PRECISION,
ADD COLUMN     "dishonourFee" DOUBLE PRECISION,
ADD COLUMN     "loanServiceFee" DOUBLE PRECISION,
ADD COLUMN     "maxRiskFee" DOUBLE PRECISION,
ADD COLUMN     "minRiskFee" DOUBLE PRECISION,
ADD COLUMN     "monthlyFee" DOUBLE PRECISION,
ADD COLUMN     "overdueAccountFee" DOUBLE PRECISION,
ADD COLUMN     "settlementChequeFee" DOUBLE PRECISION,
ADD COLUMN     "settlementFreeCheque" INTEGER,
ALTER COLUMN "earlyTerminationFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "extraRepaymentFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "missedPaymentPenalty" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "ongoingFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "overCounterPaymentFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "establishmentFee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "brokerageFee" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "PLLoanDetail" ADD COLUMN     "comparisonRepresentativeRate" DOUBLE PRECISION,
ADD COLUMN     "fixedRepresentativeRate" DOUBLE PRECISION;
